### ISSUE TITLE
photo tab 3

### ISSUE THREAD

**Issue by Mirtau** [magin3191/q2-project#11]
html
data formatting 
routes

**Comment by caelinsheahan** [comment]
We call bing's photo api with that player name to get a phot

**Comment by caelinsheahan** [comment]
var playerrole = personplayer.firstName+" is: "+isplayergood
                        var imageUrl3 = data3.value[0].contentUrl;
                        var imageUrl4 = data3.value[1].contentUrl;
                        var roleplayer =  $('<h2>').html(playerrole)
                        var playerImage3 = $('<img>').attr('src', imageUrl3);
                        var playerImage4 = $('<img>').attr('src', imageUrl4);
                        $(".playerrole1").append(roleplayer,playerImage3)
                        $(".playerrole2").append(playerImage4)

                        $.ajax({
                            url: "https://api.cognitive.microsoft.com/bing/v7.0/news/search?q="+playerNewsID+"&mkt=en-us",
                            beforeSend: function(xhrObj) {
                              // Request headers
                              xhrObj.setRequestHeader("Ocp-Apim-Subscription-Key", "d9c75868d25d4db1b924ecd9d4bacf02");
                            },
                            type: "GET",
                            // Request body
                            data: "",
                          })
                          .done(function(data4) {
                                    var playerNews = "Recent News:"
                                    var newsbreak = $('<br>')
                                    var headline1 = data4.value[0].name;
                                    var headline2= data4.value[1].name;
                                    var headline1Link = data4.value[0].url;
                                    var headline2Link = data4.value[1].url;
                                    var newsheader = $('<h3>').html(playerNews)
                                    var link1 = $('<a>').html(headline1Link)
                                    var link2 = $('<a>').html(headline2Link)
                                    link1.attr('href',headline1Link)
                                    link2.attr('href',headline2Link)
                                    var postHL1 =  $('<li>').html(headline1)
                                    var postHL2 =  $('<li>').html(headline2)
                                    $(".playernews").append(newsheader,newsbreak,postHL1,link1,newsbreak,postHL2,link2)

                          })
                          .fail(function() {
                            alert("error");
                          });
