### ISSUE TITLE
results page

### ISSUE THREAD

**Issue by RossTienken** [magin3191/q2-project#3]
As a user, I should be able to view and interact with the results page

**Comment by Mirtau** [comment]
as a user I should be able to pick the type of graph I want data displayed in (stretch goal)

**Comment by magin3191** [comment]
As a user I should be able to search for specific stats, and see the correlations between them.

**Comment by magin3191** [comment]
As I user I want to be able to filter stats

**Comment by magin3191** [comment]
-page html

**Comment by magin3191** [comment]
Page CSS

**Comment by magin3191** [comment]
Page routing
